export const Icons = {
  ic_close_24:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_close_circle.png',
  ic_close_circle_full:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/24_navigation_close_circle_full.png',
  ic_close_x_24:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/24_navigation_close.png',
  ic_check_24:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_check_green.png',
  ic_warning_24:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_warning.png',
  ic_location_24:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_location_mark.png',
  ic_round_momo_tiny:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_image/ic_momo.png',
  ic_checkbox_checked_24:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_checkbox_checked_24.png',
  ic_checkbox_unchecked_24:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_checkbox_unchecked_24.png',
  ic_check_mini:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_check_mini.png',
  ic_eye_24:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_eye.png',
  ic_order_film_gif:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_order_film.gif',
  ic_backspace_24:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_backspace.png',
  ic_momo:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_image/ic_common_logo_momo.png',
  ic_line: 'https://cdn.mservice.com.vn/app/img/kits/icons/ic_line.png',
  ic_momo_small_bottom_left:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_image/ic_momo_small.png',
  ic_arrow_drop_down_24:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_down.png',
  ic_discount_voucher:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_discount_voucher.png',
  ic_arrow_next:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_arrow_next.png',
  ic_back_arrow:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_arrow_back.png',
  ic_star_selected:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_star_yellow.png',
  ic_star: 'https://cdn.mservice.com.vn/app/img/kits/icons/ic_star_big.png',
  ic_success_process_white:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_icon/ic_check_white.png',
  ic_camera_circle:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_camera_circle.png',
  ic_transaction_history_status_fail:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_status_fail.png',
  ic_transaction_history_status_success:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_status_success.png',
  ic_transaction_history_status_processing:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_status_processing.png',
  ic_film_pin:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_image/ic_film_Pin.png',
  ic_film_ticket:
    'https://img.mservice.io/momo_app_v2/new_version/img/appx_image/ic_ticket.png',
  ic_warning: 'https://cdn.mservice.com.vn/app/img/kits/icons/ic_warning.png',
  ic_plus: 'https://cdn.mservice.com.vn/app/img/kits/icons/ic_plus.png',
  ic_calendar: 'https://cdn.mservice.com.vn/app/img/kits/icons/ic_calendar.png',
  ic_assistant:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_assistant.png',
  ic_arrow_assistant:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_arrow_assistant.png',
  icon_location_snakebar:
    'https://cdn.mservice.com.vn/app/img/kits/icons/icon_location_snakebar.png',
  ic_info_gray:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_info_gray.png',
  ic_tag_voucher: 'https://cdn.mservice.com.vn/app/img/kits/icons/ic_tag.png',
  ic_step_active:
    'https://cdn.mservice.com.vn/app/img/kits/icons/step_active.png',
  ic_step_coming:
    'https://cdn.mservice.com.vn/app/img/kits/icons/step_coming.png',
  ic_notification_info:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_notification_info.png',
  ic_cinema_poster:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_cinema_poster.png',
  ic_momo_gift:
    'https://cdn.mservice.com.vn/app/img/kits/icons/ic_momo_gift.png',
};
