import Thumb from './Thumb';
export * from './Box';
export * from './Circle';
export * from './Text';
export * from './types';
// export * from './Provider';
export * from './Alert';
export * from './Button';
export * from './Input';
export * from './Utils';
export * from './Popup';
export { Thumb };
export * from './Responsive';
export * from './IphoneXHelper';
export { Color } from './Color';
export { Icons as Icon } from './Icon';
export * from './Spacing';
export * from './DatePicker';
export * from './AppLanguage';
